name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --no-restore --configuration Release

    - name: Run tests
      run: dotnet test Backend.Tests/Backend.Tests.csproj --no-build --verbosity normal

  # deploy-backend:
  #   name: Deploy Backend to Azure App Service
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v3

  #   - name: Login to Azure
  #     uses: azure/login@v1
  #     with:
  #       creds: ${{ secrets.AZURE_CREDENTIALS }}

  #   - name: Deploy to Azure App Service
  #     uses: azure/webapps-deploy@v2
  #     with:
  #       app-name: 'your-backend-app-name'
  #       slot-name: 'production'
  #       package: ./Backend/bin/Release/net9.0/publish

  # deploy-frontend:
  #   name: Deploy Frontend to Azure Static Web Apps
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v3

  #   - name: Build frontend
  #     run: |
  #       cd Frontend
  #       dotnet publish -c Release -o build

  #   - name: Deploy to Azure Static Web Apps
  #     uses: Azure/static-web-apps-deploy@v1
  #     with:
  #       action: 'upload'
  #       app_location: './Frontend/build'
  #       api_location: ''
  #       output_location: ''
  #       azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}